<?php

return array(
	'addonsStyle'=>array(
		'title'=>'使用风格',
		'type'=>'select',
		'options'=>[
            'default'=>'默认风格'
		],
		'value'=>'',
		'tips'=>''
	),
	'seoPintuanKeywords'=>array(
		'title'=>'拼团SEO关键字',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'seoPintuanDesc'=>array(
		'title'=>"拼团SEO描述",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'goodsShareTitle'=>array(
		'title'=>'商品分享标题',
		'type'=>'text',
		'value'=>''
	)
);
