<?php

return array(
	'seoAuctionKeywords'=>array(
		'title'=>'拍卖SEO关键字',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'seoAuctionDesc'=>array(
		'title'=>"拍卖SEO描述",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'endPayDate'=>array(
        'title'=>'货款支付期限（天）',
        'type'=>'text',
		'value'=>'3',
		'tips'=>''
	),
	'auctionArticleId'=>array(
		'title'=>"拍卖文章说明ID",
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'goodsShareTitle'=>array(
		'title'=>'商品分享标题',
		'type'=>'text',
		'value'=>''
	)
);
